apiVersion: v1
kind: Service
metadata:
  name: capper-kubernetes-webhook
  namespace: capper
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: capper-kubernetes-webhook