apiVersion: v1
kind: Service
metadata:
  name: capper-kubernetes-webhook
  namespace: capper
spec:
  type: ExternalName
  externalName: capper-kubernetes-webhook.capper.svc
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: capper-kubernetes-webhook
