apiVersion: apps/v1
kind: Deployment
metadata:
  name: enforcer-test
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - image: centos:7
        imagePullPolicy: IfNotPresent
        name: centos
        resources:
          limits:
            memory: "500Mi"
            cpu: "2"
          requests:
            memory: "500Mi"
            cpu: "2"
        stdin: true
        tty: true
