apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
 name: "capper-kubernetes-webhook"
webhooks:
 - name: "capper-kubernetes-webhook.capper.svc"
   namespaceSelector:
     matchLabels:
       admission-webhook: enabled
   rules:
     - apiGroups: [""]
       apiVersions: ["v1"]
       operations: ["CREATE"]
       resources: ["pods"]
       scope: "*"
   clientConfig:
     service:
       namespace: capper
       name: capper-kubernetes-webhook
       path: /validate/deployments
       port: 443
     caBundle: LS0tLS1...
   admissionReviewVersions: ["v1beta1"]
   sideEffects: None