apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
 name: "capper-kubernetes-hook.capper.svc"
webhooks:
 - name: "capper-kubernetes-hook.capper.svc"
   namespaceSelector:
     matchLabels:
       admission-webhook: enabled
   rules:
     - apiGroups: [""]
       apiVersions: ["v1"]
       operations: ["CREATE"]
       resources: ["pods"]
       scope: "*"
   clientConfig:
     service:
       namespace: capper
       name: capper-kubernetes-webhook
       path: /mutate/pods
       port: 443
     caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzREND...
